/* generated by neslua from main.lua - edit the .lua, not this file */
#include "nes_api.h"
#include "nes_math.h"

static void gtl__init(void);
static void gtl__draw(void);

static void gtl__init(void)
{
    nes_canvas_at(8, 6, 12, 8);
    (nes_a0 = 1, nes_a1 = 1, nes_a2 = 62, nes_a3 = 46, nes_a4 = 2, nes_rect_z());
    (nes_a0 = 1, nes_a1 = 1, nes_a2 = 62, nes_a3 = 46, nes_a4 = 2, nes_line_z());
    (nes_a0 = 62, nes_a1 = 1, nes_a2 = 1, nes_a3 = 46, nes_a4 = 2, nes_line_z());
    (nes_a0 = 32, nes_a1 = 24, nes_a2 = 10, nes_a3 = 2, nes_circfill_z());
    (nes_a0 = 32, nes_a1 = 24, nes_a2 = 16, nes_a3 = 2, nes_circ_z());
}

static void gtl__draw(void)
{
    nes_cls(15);
}

void main(void)
{
    nes_init();
    gtl__init();
    for (;;) {
        nes_update_inputs();
        nes_oam_clear();
        gtl__draw();
        nes_endframe();
    }
}
