/* generated by neslua from main.lua - edit the .lua, not this file */
#include "nes_api.h"
#include "nes_math.h"

static void lcl__update60(void);
static void lcl__draw(void);

int lcl_x = 120;
int lcl_y = 120;

static void lcl__update60(void)
{
    if (((nes_pad0 & 256u) != 0)) {
        lcl_x = (lcl_x + 2);
    }
    if (((nes_pad0 & 512u) != 0)) {
        lcl_x = (lcl_x - 2);
    }
    if (((nes_pad0 & 1028u) != 0)) {
        lcl_y = (lcl_y + 2);
    }
    if (((nes_pad0 & 2056u) != 0)) {
        lcl_y = (lcl_y - 2);
    }
}

static void lcl__draw(void)
{
    nes_cls(15);
    nes_print("hello neslua", 72, 88, 48);
    nes_spal(1);
    (nes_a0 = 0, nes_a1 = lcl_x, nes_a2 = lcl_y, nes_a3 = 2, nes_a4 = 2, nes_a5 = 0 | (0 << 1), nes_spr_z());
}

void main(void)
{
    nes_init();
    for (;;) {
        nes_update_inputs();
        nes_oam_clear();
        lcl__update60();
        lcl__draw();
        nes_endframe();
    }
}
