/* generated by neslua from main.lua - edit the .lua, not this file */
#include "nes_api.h"
#include "nes_math.h"

static void lcl_setup(void);
static void lcl__init(void);
static void lcl_fire(void);
static void lcl_reset_game(void);
static void lcl__update(void);
static void lcl__draw(void);

int lcl_px = 120;
int lcl_py = 196;
int lcl_pcool = 0;
int lcl_bx[6];
int lcl_by[6];
unsigned char lcl_ba[6];
int lcl_enx[12];
int lcl_eny[12];
unsigned char lcl_eal[12];
int lcl_edir = 1;
int lcl_edx = 0;
int lcl_alive = 12;
int lcl_lex = 0;
int lcl_ley = 0;
int lcl_let = 0;
int lcl_score = 0;
int lcl_lives = 3;
int lcl_state = 0;
int lcl_drawn = 0;
int lcl_starstep = 0;
int lcl_hudscore = -1;

static void lcl_setup(void)
{
    { unsigned char lcl_i = 1; unsigned char L_lim0 = 12;
        for (; lcl_i <= L_lim0; ++lcl_i) {
            { int lcl_col = nes_ifmod((lcl_i - 1), 6);
                { int lcl_row = nes_ifdiv((lcl_i - 1), 6);
                    lcl_enx[lcl_i - 1] = (24 + (((lcl_col) << 5) + ((lcl_col) << 3)));
                    lcl_eny[lcl_i - 1] = ((28 + (((lcl_row) << 5) + ((lcl_row) << 4))) + ((((lcl_col & 1)) << 4)));
                    (lcl_eal - 1)[lcl_i] = 1;
                }
            }
        }
    }
    { unsigned char lcl_i = 1; unsigned char L_lim1 = 6;
        for (; lcl_i <= L_lim1; ++lcl_i) {
            (lcl_ba - 1)[lcl_i] = 0;
        }
    }
}

static void lcl__init(void)
{
    lcl_setup();
}

static void lcl_fire(void)
{
    { unsigned char lcl_i = 1; unsigned char L_lim2 = 6;
        for (; lcl_i <= L_lim2; ++lcl_i) {
            if (((unsigned char)(lcl_ba - 1)[lcl_i] == (unsigned char)0)) {
                lcl_bx[lcl_i - 1] = (lcl_px + 4);
                lcl_by[lcl_i - 1] = (lcl_py - 8);
                (lcl_ba - 1)[lcl_i] = 1;
                nes_sfx(0, -1);
                return;
            }
        }
    }
}

static void lcl_reset_game(void)
{
    lcl_px = 120;
    lcl_py = 196;
    lcl_pcool = 0;
    lcl_edir = 1;
    lcl_edx = 0;
    lcl_alive = 12;
    lcl_let = 0;
    lcl_score = 0;
    lcl_lives = 3;
    lcl_state = 0;
    lcl_drawn = 0;
    lcl_starstep = 0;
    lcl_hudscore = (-1);
    lcl_setup();
}

static void lcl__update(void)
{
    if ((lcl_state != 0)) {
        if (((nes_rpt0 & 16u) != 0)) {
            lcl_reset_game();
        }
        return;
    }
    if (((nes_pad0 & 512u) != 0)) {
        lcl_px = (lcl_px - 3);
    }
    if (((nes_pad0 & 256u) != 0)) {
        lcl_px = (lcl_px + 3);
    }
    if ((lcl_px < 8)) {
        lcl_px = 8;
    }
    if ((lcl_px > 232)) {
        lcl_px = 232;
    }
    if ((lcl_pcool > 0)) {
        lcl_pcool = (lcl_pcool - 1);
    }
    if ((((nes_pad0 & 16u) != 0) && (lcl_pcool == 0))) {
        lcl_fire();
        lcl_pcool = 8;
    }
    { unsigned char lcl_i = 1; unsigned char L_lim3 = 6;
        for (; lcl_i <= L_lim3; ++lcl_i) {
            if (((unsigned char)(lcl_ba - 1)[lcl_i] != (unsigned char)0)) {
                lcl_by[lcl_i - 1] = ((lcl_by - 1)[lcl_i] - 6);
                if (((lcl_by - 1)[lcl_i] < 0)) {
                    (lcl_ba - 1)[lcl_i] = 0;
                }
            }
        }
    }
    lcl_edx = (lcl_edx + lcl_edir);
    if ((lcl_edx > 20)) {
        lcl_edir = (-1);
    }
    if (((lcl_edx - ((-20))) < 0)) {
        lcl_edir = 1;
    }
    if ((lcl_let > 0)) {
        lcl_let = (lcl_let - 1);
    }
    { unsigned char lcl_e = 1; unsigned char L_lim4 = 12;
        for (; lcl_e <= L_lim4; ++lcl_e) {
            if (((unsigned char)(lcl_eal - 1)[lcl_e] != (unsigned char)0)) {
                { int lcl_ex = ((lcl_enx - 1)[lcl_e] + lcl_edx);
                    { int lcl_ey = (lcl_eny - 1)[lcl_e];
                        if ((lcl_ey > 176)) {
                            lcl_state = 2;
                            return;
                        }
                        { unsigned char lcl_i = 1; unsigned char L_lim5 = 6;
                            for (; lcl_i <= L_lim5; ++lcl_i) {
                                if (((unsigned char)(lcl_ba - 1)[lcl_i] != (unsigned char)0)) {
                                    { int lcl_dx = ((lcl_bx - 1)[lcl_i] - lcl_ex);
                                        { int lcl_dy = ((lcl_by - 1)[lcl_i] - lcl_ey);
                                            if ((((((lcl_dx - ((-12))) > 0) && (lcl_dx < 12)) && ((lcl_dy - ((-12))) > 0)) && (lcl_dy < 12))) {
                                                (lcl_eal - 1)[lcl_e] = 0;
                                                (lcl_ba - 1)[lcl_i] = 0;
                                                lcl_score = (lcl_score + 10);
                                                lcl_alive = (lcl_alive - 1);
                                                lcl_lex = lcl_ex;
                                                lcl_ley = lcl_ey;
                                                lcl_let = 12;
                                                nes_sfx(0, -1);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    if ((lcl_alive <= 0)) {
        lcl_state = 1;
    }
}

static void lcl__draw(void)
{
    if ((lcl_drawn == 0)) {
        nes_cls(2);
        nes_print("score", 8, 8, 48);
        nes_print("lives", 200, 8, 48);
        lcl_drawn = 1;
    }
    if ((lcl_starstep < 24)) {
        { int lcl_i = (lcl_starstep + 1);
            { int lcl_sx = (nes_ifmod((((lcl_i) << 6) - ((lcl_i) << 4) - (lcl_i)), 30) + 1);
                { int lcl_sy = (nes_ifmod((lcl_i * 71), 22) + 3);
                    nes_print(".", (((lcl_sx) << 3)), (((lcl_sy) << 3)), 16);
                    nes_print(".", ((((nes_ifmod((((lcl_i) << 5) - ((lcl_i) << 1) - (lcl_i)), 30) + 1)) << 3)), ((((nes_ifmod((lcl_i * 53), 22) + 3)) << 3)), 48);
                    lcl_starstep = (lcl_starstep + 2);
                }
            }
        }
    }
    if ((lcl_state == 1)) {
        nes_print("you win", 96, 112, 42);
        nes_print("press b", 96, 128, 17);
        return;
    }
    if ((lcl_state == 2)) {
        nes_print("game over", 88, 112, 22);
        nes_print("press b", 96, 128, 17);
        return;
    }
    if (((lcl_score - (lcl_hudscore)) != 0)) {
        nes_print_int(lcl_score, 56, 8, 40);
        nes_print_int(lcl_lives, 248, 8, 22);
        lcl_hudscore = lcl_score;
    }
    nes_spal(0);
    { unsigned char lcl_e = 1; unsigned char L_lim6 = 12;
        for (; lcl_e <= L_lim6; ++lcl_e) {
            if (((unsigned char)(lcl_eal - 1)[lcl_e] != (unsigned char)0)) {
                (nes_a0 = 2, nes_a1 = ((lcl_enx - 1)[lcl_e] + lcl_edx), nes_a2 = (lcl_eny - 1)[lcl_e], nes_a3 = 2, nes_a4 = 2, nes_a5 = 0 | (0 << 1), nes_spr_z());
            }
        }
    }
    if ((lcl_let > 0)) {
        nes_spal(3);
        (nes_a0 = 4, nes_a1 = lcl_lex, nes_a2 = lcl_ley, nes_a3 = 2, nes_a4 = 2, nes_a5 = 0 | (0 << 1), nes_spr_z());
    }
    nes_spal(2);
    { unsigned char lcl_i = 1; unsigned char L_lim7 = 6;
        for (; lcl_i <= L_lim7; ++lcl_i) {
            if (((unsigned char)(lcl_ba - 1)[lcl_i] != (unsigned char)0)) {
                (nes_a0 = 8, nes_a1 = (lcl_bx - 1)[lcl_i], nes_a2 = (lcl_by - 1)[lcl_i], nes_a3 = 1, nes_a4 = 1, nes_a5 = 0 | (0 << 1), nes_spr_z());
            }
        }
    }
    nes_spal(1);
    (nes_a0 = 0, nes_a1 = lcl_px, nes_a2 = lcl_py, nes_a3 = 2, nes_a4 = 2, nes_a5 = 0 | (0 << 1), nes_spr_z());
}

void main(void)
{
    unsigned char _nes_odd = 0;
    nes_init();
    nes_audio_init();
    lcl__init();
    for (;;) {
        nes_update_inputs();
        nes_oam_clear();
        if (_nes_odd == 0) {
            lcl__update();
        }
        _nes_odd ^= 1;
        lcl__draw();
        nes_endframe();
    }
}
