/* generated by neslua from synth-fornum.lua - edit the .lua, not this file */
#include "nes_api.h"
#include "nes_math.h"

static void lcl__update(void);
static void lcl__draw(void);

static void lcl__update(void)
{
    { int lcl_i = 0; int L_lim0 = 255;
        for (; lcl_i <= L_lim0; ++lcl_i) {
        }
    }
    { int lcl_j = 1; int L_lim1 = 10;
        for (; lcl_j <= L_lim1; lcl_j += 2) {
        }
    }
}

static void lcl__draw(void)
{
}

void main(void)
{
    unsigned char _nes_odd = 0;
    nes_init();
    for (;;) {
        nes_update_inputs();
        nes_oam_clear();
        if (_nes_odd == 0) {
            lcl__update();
        }
        _nes_odd ^= 1;
        lcl__draw();
        nes_endframe();
    }
}
