/* generated by neslua from synth-array.lua - edit the .lua, not this file */
#include "nes_api.h"
#include "nes_math.h"

static void gtl__update(void);
static void gtl__draw(void);

int gtl_a[16];
unsigned char gtl_b[8];

static void gtl__update(void)
{
    gtl_a[0] = 5;
    gtl_b[0] = 2;
}

static void gtl__draw(void)
{
}

void main(void)
{
    unsigned char _nes_odd = 0;
    nes_init();
    for (;;) {
        nes_update_inputs();
        nes_oam_clear();
        if (_nes_odd == 0) {
            gtl__update();
        }
        _nes_odd ^= 1;
        gtl__draw();
        nes_endframe();
    }
}
