/* generated by neslua from synth-func.lua - edit the .lua, not this file */
#include "nes_api.h"
#include "nes_math.h"

static int gtl_helper(void);
static void gtl__update(void);
static void gtl__draw(void);

static int gtl_helper(void)
{
    return (nes_p0 + nes_p1);
}

static void gtl__update(void)
{
    { int gtl_z = (((1) + (2)));
    }
}

static void gtl__draw(void)
{
}

void main(void)
{
    unsigned char _nes_odd = 0;
    nes_init();
    for (;;) {
        nes_update_inputs();
        nes_oam_clear();
        if (_nes_odd == 0) {
            gtl__update();
        }
        _nes_odd ^= 1;
        gtl__draw();
        nes_endframe();
    }
}
