/* generated by neslua from synth-btn.lua - edit the .lua, not this file */
#include "nes_api.h"
#include "nes_math.h"

static void lcl__update(void);
static void lcl__draw(void);

static void lcl__update(void)
{
    if (((nes_pad0 & 512u) != 0)) {
    }
    if (((nes_rpt0 & 16u) != 0)) {
    }
}

static void lcl__draw(void)
{
}

void main(void)
{
    unsigned char _nes_odd = 0;
    nes_init();
    for (;;) {
        nes_update_inputs();
        nes_oam_clear();
        if (_nes_odd == 0) {
            lcl__update();
        }
        _nes_odd ^= 1;
        lcl__draw();
        nes_endframe();
    }
}
