/* generated by neslua from synth-minmax.lua - edit the .lua, not this file */
#include "nes_api.h"
#include "nes_math.h"

static void gtl__update(void);
static void gtl__draw(void);

static void gtl__update(void)
{
    { int gtl_a = (((unsigned char)1 < (unsigned char)2) ? (1) : (2));
        { int gtl_b = (((unsigned char)3 > (unsigned char)4) ? (3) : (4));
            { int gtl_c = (((unsigned char)1 < (unsigned char)2) ? (((unsigned char)2 < (unsigned char)3) ? (2) : (((unsigned char)1 < (unsigned char)3) ? (3) : (1))) : (((unsigned char)1 < (unsigned char)3) ? (1) : (((unsigned char)2 < (unsigned char)3) ? (3) : (2))));
                { int gtl_d = nes_absi((-5));
                }
            }
        }
    }
}

static void gtl__draw(void)
{
}

void main(void)
{
    unsigned char _nes_odd = 0;
    nes_init();
    for (;;) {
        nes_update_inputs();
        nes_oam_clear();
        if (_nes_odd == 0) {
            gtl__update();
        }
        _nes_odd ^= 1;
        gtl__draw();
        nes_endframe();
    }
}
