/* generated by neslua from synth-spr.lua - edit the .lua, not this file */
#include "nes_api.h"
#include "nes_math.h"

static void gtl__update(void);
static void gtl__draw(void);

int gtl_x = 0;

static void gtl__update(void)
{
    gtl_x = (gtl_x + 1);
}

static void gtl__draw(void)
{
    nes_cls(2);
    (nes_a0 = 1, nes_a1 = gtl_x, nes_a2 = 50, nes_a3 = 1, nes_a4 = 1, nes_a5 = 0 | (0 << 1), nes_spr_z());
}

void main(void)
{
    unsigned char _nes_odd = 0;
    nes_init();
    for (;;) {
        nes_update_inputs();
        nes_oam_clear();
        if (_nes_odd == 0) {
            gtl__update();
        }
        _nes_odd ^= 1;
        gtl__draw();
        nes_endframe();
    }
}
