/* generated by neslua from synth-fixedmath.lua - edit the .lua, not this file */
#include "nes_api.h"
#include "nes_math.h"

static void lcl__update(void);
static void lcl__draw(void);

long lcl_x = 0L; /* 0 */

static void lcl__update(void)
{
    lcl_x = (lcl_x + 32768L /* 0.5 */);
    lcl_x = (fa = lcl_x, fb = 196608L, nes_fdiv_zp());
    lcl_x = (lcl_x & 131071L);
}

static void lcl__draw(void)
{
}

void main(void)
{
    unsigned char _nes_odd = 0;
    nes_init();
    for (;;) {
        nes_update_inputs();
        nes_oam_clear();
        if (_nes_odd == 0) {
            lcl__update();
        }
        _nes_odd ^= 1;
        lcl__draw();
        nes_endframe();
    }
}
