/* generated by neslua from synth-func.lua - edit the .lua, not this file */
#include "nes_api.h"
#include "nes_math.h"

static int lcl_helper(void);
static void lcl__update(void);
static void lcl__draw(void);

static int lcl_helper(void)
{
    return (nes_p0 + nes_p1);
}

static void lcl__update(void)
{
    { int lcl_z = (((1) + (2)));
    }
}

static void lcl__draw(void)
{
}

void main(void)
{
    unsigned char _nes_odd = 0;
    nes_init();
    for (;;) {
        nes_update_inputs();
        nes_oam_clear();
        if (_nes_odd == 0) {
            lcl__update();
        }
        _nes_odd ^= 1;
        lcl__draw();
        nes_endframe();
    }
}
