/* generated by neslua from synth-fixedmath.lua - edit the .lua, not this file */
#include "nes_api.h"
#include "nes_math.h"

static void gtl__update(void);
static void gtl__draw(void);

long gtl_x = 0L; /* 0 */

static void gtl__update(void)
{
    gtl_x = (gtl_x + 32768L /* 0.5 */);
    gtl_x = (fa = gtl_x, fb = 196608L, nes_fdiv_zp());
    gtl_x = (gtl_x & 131071L);
}

static void gtl__draw(void)
{
}

void main(void)
{
    unsigned char _nes_odd = 0;
    nes_init();
    for (;;) {
        nes_update_inputs();
        nes_oam_clear();
        if (_nes_odd == 0) {
            gtl__update();
        }
        _nes_odd ^= 1;
        gtl__draw();
        nes_endframe();
    }
}
