/* generated by neslua from synth-array.lua - edit the .lua, not this file */
#include "nes_api.h"
#include "nes_math.h"

static void lcl__update(void);
static void lcl__draw(void);

int lcl_a[16];
unsigned char lcl_b[8];

static void lcl__update(void)
{
    lcl_a[0] = 5;
    lcl_b[0] = 2;
}

static void lcl__draw(void)
{
}

void main(void)
{
    unsigned char _nes_odd = 0;
    nes_init();
    for (;;) {
        nes_update_inputs();
        nes_oam_clear();
        if (_nes_odd == 0) {
            lcl__update();
        }
        _nes_odd ^= 1;
        lcl__draw();
        nes_endframe();
    }
}
