/* generated by neslua from synth-fornum.lua - edit the .lua, not this file */
#include "nes_api.h"
#include "nes_math.h"

static void gtl__update(void);
static void gtl__draw(void);

static void gtl__update(void)
{
    { int gtl_i = 0; int L_lim0 = 255;
        for (; gtl_i <= L_lim0; ++gtl_i) {
        }
    }
    { int gtl_j = 1; int L_lim1 = 10;
        for (; gtl_j <= L_lim1; gtl_j += 2) {
        }
    }
}

static void gtl__draw(void)
{
}

void main(void)
{
    unsigned char _nes_odd = 0;
    nes_init();
    for (;;) {
        nes_update_inputs();
        nes_oam_clear();
        if (_nes_odd == 0) {
            gtl__update();
        }
        _nes_odd ^= 1;
        gtl__draw();
        nes_endframe();
    }
}
